<?php

/**
 * Implements hook_theme().
 */
function employees_record_theme($existing, $type, $theme, $path) {
  return [
    'salary_list' => [
      'variables' => [
        'header' => NULL,
        'rows' => NULL,
      ],
      'template' => 'salary-list', // This corresponds to the template file.
    ],

    'personal_info_form' => [
      'render element' => 'form',
      'template' => 'personal-info-form',
    ],

  ];
}