<?php

function my_custom_router_theme($existing, $type, $theme, $path) {

 
  return [
    
    'demo_page' => [
  

      'variables' => [

       'text' => 'Default value',
       'arr'=> [],

      ],
    ],  

    'arguments_display' => [

      'variables' => [
        'num1'=> null,
        'num2'=> null,

      ],
    ],

    'custom_test_pages_content_array' => [
      
      'render element' => 'element',
    ],
    
    
    'item_list' => [
      
      'variables' => [
        'title' => NULL,
        'items' => NULL,
      ],
    ],

    'custom_test_pages_list' => [
      
      'variables' => [
        'title' => NULL,
        'items' => NULL,
      ],
    ],


        
    'arguments_test_page' => [
      
      'variables' => [
        'strg1' => NULL,
        'strg2' => NULL,
      ],
    ],


    'custom_form'  => [

      'render element' => 'form',
      'template' => 'custom-form',

    ],

      
];

}

 
